## Ejercicio 3: Inspección visual de productos

### Ficha PEAS

<table>
<tr>
<th>Componente</th>
<th>Descripción</th>
</tr>

<tr>
<td><strong>Percepción (S)</strong></td>
<td>
<ul>
<li><strong>Matriz de inspección:</strong> matriz de 5×5 capturada por una cámara, donde cada posición representa una zona del producto.</li>
<li><strong>Valor 0:</strong> zona normal o sin defecto.</li>
<li><strong>Valor 1:</strong> zona que presenta un defecto.</li>
<li><strong>Cantidad de defectos:</strong> número total de posiciones con valor 1 en la matriz.</li>
</ul>
</td>
</tr>

<tr>
<td><strong>Entorno (E)</strong></td>
<td>
Sistema automatizado de inspección visual encargado de verificar productos mediante una cámara antes de su aprobación.
</td>
</tr>

<tr>
<td><strong>Acciones (A)</strong></td>
<td>
<ul>
<li><strong>Aprobar:</strong> el producto no presenta defectos.</li>
<li><strong>Enviar a revisión manual:</strong> el producto presenta entre 1 y 3 defectos.</li>
<li><strong>Rechazar:</strong> el producto presenta más de 3 defectos.</li>
</ul>
</td>
</tr>

<tr>
<td><strong>Medida de desempeño (P)</strong></td>
<td>
Clasificar correctamente los productos según la cantidad de defectos detectados, evitando aprobar productos defectuosos y reduciendo revisiones manuales innecesarias.
</td>
</tr>

</table>

### Justificación de las reglas

Las reglas se basan en la cantidad de defectos detectados en la matriz de inspección. Si no se detectan defectos, el producto se aprueba directamente. Cuando se encuentran entre 1 y 3 defectos, el producto se envía a revisión manual para realizar una evaluación adicional. Si se detectan más de 3 defectos, el producto se rechaza debido al mayor nivel de deterioro identificado.

### Código

El agente recibe una matriz de 5×5 y cuenta la cantidad de posiciones que presentan defectos. Según el número de defectos detectados, determina si el producto debe aprobarse, enviarse a revisión manual o rechazarse.

In [1]:
import numpy as np

def agente_inspeccion(matriz):
    
    # Convertir la matriz a un arreglo de NumPy
    matriz = np.array(matriz)

    # Contar la cantidad de defectos (valores 1)
    cantidad_defectos = np.sum(matriz == 1)

    # Regla 1: ningún defecto
    if cantidad_defectos == 0:
        return (
            "aprobar",
            "no se detectaron defectos en el producto"
        )

    # Regla 2: entre 1 y 3 defectos
    elif cantidad_defectos <= 3:
        return (
            "revisión manual",
            f"se detectaron {cantidad_defectos} defectos"
        )

    # Regla 3: más de 3 defectos
    else:
        return (
            "rechazar",
            f"se detectaron {cantidad_defectos} defectos"
        )

### Simulación y pruebas

Se prueban diferentes matrices de inspección de 5×5 para verificar el comportamiento del agente. Las pruebas incluyen un producto sin defectos, casos con una cantidad intermedia de defectos y casos que superan el límite establecido para el rechazo. También se incluye el caso límite de 3 y 4 defectos para comprobar el cambio entre revisión manual y rechazo.

In [3]:
# Matrices de prueba para el agente de inspección

pruebas = [
    # Caso 1: 0 defectos -> aprobar
    np.array([
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]
    ]),

    # Caso 2: 1 defecto -> revisión manual
    np.array([
        [0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]
    ]),

    # Caso 3: 3 defectos -> revisión manual (límite)
    np.array([
        [1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]
    ]),

    # Caso 4: 4 defectos -> rechazar (límite)
    np.array([
        [1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0]
    ]),

    # Caso 5: 6 defectos -> rechazar
    np.array([
        [1, 1, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]
    ])
]

for i, matriz in enumerate(pruebas, start=1):

    cantidad_defectos = np.sum(matriz == 1)

    accion, motivo = agente_inspeccion(matriz)

    print(f"PRUEBA {i}")
    print("Matriz:")
    print(matriz)
    print(f"Cantidad de defectos: {cantidad_defectos}")
    print(f"Acción: {accion}")
    print(f"Motivo: {motivo}")
    print("-" * 60)

PRUEBA 1
Matriz:
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Cantidad de defectos: 0
Acción: aprobar
Motivo: no se detectaron defectos en el producto
------------------------------------------------------------
PRUEBA 2
Matriz:
[[0 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Cantidad de defectos: 1
Acción: revisión manual
Motivo: se detectaron 1 defectos
------------------------------------------------------------
PRUEBA 3
Matriz:
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Cantidad de defectos: 3
Acción: revisión manual
Motivo: se detectaron 3 defectos
------------------------------------------------------------
PRUEBA 4
Matriz:
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 0]]
Cantidad de defectos: 4
Acción: rechazar
Motivo: se detectaron 4 defectos
------------------------------------------------------------
PRUEBA 5
Matriz:
[[1 1 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
Cantidad de defe